"""Verify signed SimpulseID example artifacts generated by ``src/sign_examples.py``.

This script validates the ignored ``examples/signed/`` output directory using
the real Harbour JOSE verification functions.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from harbour.verifier import verify_vc_jose, verify_vp_jose

from sign_examples import (
    REPO_ROOT,
    SIGNED_DIR,
    discover_examples,
    load_test_p256_keypair,
)


@dataclass
class VerificationCounts:
    """Summary counters for verified example artifacts."""

    credentials: int = 0
    evidence_presentations: int = 0


def _assert_has_type(payload: dict, expected_type: str, source: Path) -> None:
    types = payload.get("type", [])
    if isinstance(types, str):
        types = [types]
    if expected_type not in types:
        raise RuntimeError(
            f"{source} does not contain expected type {expected_type!r}: {types!r}"
        )


def main() -> None:
    _, public_key = load_test_p256_keypair()
    expected_examples = {prefix for _, prefix in discover_examples()}
    if not SIGNED_DIR.is_dir():
        raise RuntimeError(
            "No signed example directory found. Run `make story-sign` first."
        )

    signed_credentials = sorted(
        path for path in SIGNED_DIR.glob("*.jwt") if ".evidence-vp." not in path.name
    )
    if not signed_credentials:
        raise RuntimeError("No signed VC JWTs found. Run `make story-sign` first.")

    found_examples = {path.stem for path in signed_credentials}
    missing = sorted(expected_examples - found_examples)
    if missing:
        raise RuntimeError(
            "Missing signed artifacts for examples: " + ", ".join(missing)
        )

    counts = VerificationCounts()
    for jwt_path in signed_credentials:
        vc_jwt = jwt_path.read_text(encoding="utf-8").strip()
        vc_payload = verify_vc_jose(vc_jwt, public_key)
        _assert_has_type(vc_payload, "VerifiableCredential", jwt_path)
        counts.credentials += 1

        evidence_jwt_path = jwt_path.with_name(f"{jwt_path.stem}.evidence-vp.jwt")
        if not evidence_jwt_path.exists():
            continue

        vp_jwt = evidence_jwt_path.read_text(encoding="utf-8").strip()
        vp_payload = verify_vp_jose(vp_jwt, public_key)
        _assert_has_type(vp_payload, "VerifiablePresentation", evidence_jwt_path)
        counts.evidence_presentations += 1

        embedded_vps = [
            evidence.get("verifiablePresentation")
            for evidence in vc_payload.get("evidence", [])
            if isinstance(evidence, dict)
        ]
        if vp_jwt not in embedded_vps:
            raise RuntimeError(
                f"{evidence_jwt_path} was not embedded in {jwt_path} evidence chain"
            )

    print(
        f"Verified {counts.credentials} credential JWT(s) and "
        f"{counts.evidence_presentations} evidence VP JWT(s) in "
        f"{SIGNED_DIR.relative_to(REPO_ROOT)}"
    )


if __name__ == "__main__":
    main()
